syntax = "proto3";
package jetstream;

option java_package = "com.jetstream.android.proto";
option java_multiple_files = true;

message MessageWrapper {
    oneof message {
        Identity identity = 1;
        Notification notification = 2;
        Clipboard clipboard = 3;
        Action action = 4;
        Presentation presentation = 5;
    }
}

message Identity {
    string name = 1;
    string host = 2;
    uint32 port = 3;
}

message Notification {
    bool create = 1;
    uint32 id = 2;
    string title = 3;
    string body = 4;
    string app = 5;
    bytes icon = 6;
}

message Clipboard {
    string content = 1;
}

message Action {
    oneof actiontype {
        Lock lock = 1;
        Poweroff poweroff = 2;
        Reboot reboot = 3;
    }
}

message Lock {}
message Poweroff {}
message Reboot {}

message Presentation {
    oneof actiontype {
        PrevSlide prevslide = 1;
        NextSlide nextslide = 2;
        Present present = 3;
        Fullscreen fullscreen = 4;
        Visibility visibility = 5;
    }
}

message PrevSlide {}
message NextSlide {}
message Present {}
message Fullscreen {}
message Visibility {}

