syntax = "proto3";
package jetstream;

option java_package = "com.jetstream.android.proto";
option java_multiple_files = true;

message Identity {
    string name = 1;
    string host = 2;
    uint32 port = 3;
}

message MessageWrapper {
    oneof message {
        Notification notification = 1;
        Clipboard clipboard = 2;
    }
}

message Notification {
    bool create = 1;
    uint32 id = 2;
    string title = 3;
    string body = 4;
    bytes icon = 5;
}

message Clipboard {
    string content = 1;
}
